[package]
name = "dump_cli"
version = "0.1.0"
edition = "2024"
authors = ["Kylin 874067181lsfy@gmail.com"]

[dependencies]
cex-core = { path = "../cex-core" }
log = "0.4.28"
tracing-subscriber = "0.3.20"
clap = { version = "4.5.51", features = ["derive"] }
tracing = "0.1.41"
serde_json = "1.0"
anyhow = "1.0"
parquet = { version = "47.0.0", features = ["zstd"] }
serde = { version = "1.0.228", features = ["derive"] }
csv = "1.4.0"
